version: 2
jobs:
   build_push_deploy:
     docker:
       - image: hkevinchu/circleci-builder
     steps:
       - checkout
       - run: |
            echo "build job line 1"
            uptime
            pwd

workflows:
  version: 2
  build:
    jobs:
      - build_push_deploy

