version: 2
jobs:
   build:
     docker:
       - image: hkevinchu/circleci-builder
     steps:
       - checkout
       - run: |
            echo "build job line 1"
            uptime
            pwd

workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
         requires:
            - build
      - hold:
         type: approval
         requires:
            - test
      - deploy:
         requires:
            - hold
