version: 2
jobs:
   build:
     docker:
       - image: circleci/php:apache-node-browsers
     steps:
       - checkout
       - run: echo "build job complete"
   test:
     docker:
       - image: circleci/php:apache-node-browsers
     steps:
       - checkout
       - run: echo "test job complete"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
