version: 2
jobs:
   build_push_deploy:
     docker:
       - image: hkevinchu/circleci-builder
     steps:
       - checkout
       - run: |
            mkdir credentials
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key ca.pem credentials/ca.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key admin.pem credentials/admin.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key admin-key.pem credentials/admin-key.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key kubeconfig kubeconfig
            export KUBECONFIG=./kubeconfig
            make build
            make push
            make deploy
            kubectl delete pod $(kubectl get pods | grep api-nginx | cut -f1 -d' ')
            kubectl delete pod $(kubectl get pods | grep api-php | cut -f1 -d' ')
workflows:
  version: 2
  build:
    jobs:
      - build_push_deploy
         filters:
            branches:
               only:
                  - user/stratus10
