version: 2
jobs:
   build_push_and_deploy:
     docker:
       - image: hkevinchu/circleci-builder
     steps:
       - checkout
       - run: |
            mkdir -p /root/.aws
            echo > /root/.aws/config
            chmod 600 /root/.aws/config
            echo "[profile yembo]" >> /root/.aws/config
            echo "aws_access_key_id = ${AWS_ACCESS_KEY_ID}" >> /root/.aws/config
            echo "aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}" >> /root/.aws/config
            echo "default_region = ${AWS_DEFAULT_REGION}" >> /root/.aws/config
            mkdir credentials
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key ca.pem credentials/ca.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key admin.pem credentials/admin.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key admin-key.pem credentials/admin-key.pem
            aws s3api get-object --bucket ${YEMBO_SECURE_S3_BUCKET} --key kubeconfig kubeconfig
            export KUBECONFIG=./kubeconfig
            ls -alR /root/
            echo "make build"
            echo "make push"
            echo "make deploy"
            echo "kubectl delete pod $(kubectl get pods | grep ${YEMBO_MICROSERVICE} | cut -f1 -d' ')"            
            
workflows:
  version: 2
  build_push_and_deploy:
    jobs:
      - build_push_and_deploy:
          filters:
            branches:
              only: 
                - master
